name: gnotify
on:
  issues:
    types:
    - opened
    - reopened
    - closed
# See note in gnotify.py's main function regarding the known issue related to
# the thread option REPLY_MESSAGE_OR_FAIL.
#    - assigned
#    - unassigned
#    - labeled
#    - unlabeled
  issue_comment:
    types:
    - created
  pull_request:
    types:
    - opened
    - reopened
    - closed
    - review_requested
# See note in gnotify.py's main function regarding the known issue related to
# the thread option REPLY_MESSAGE_OR_FAIL.
#    - assigned
#    - unassigned
#    - labeled
#    - unlabeled
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setup
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: '.github/workflows/gnotify.requirements'
    - name: pip
      run:  pip install -r .github/workflows/gnotify.requirements
    - name: notify
      env:
        GOOGLE_SPACE_URL: ${{ secrets.GOOGLE_SPACE_URL }}
        GITHUB_ACT_OBJCT: ${{ toJSON(github) }}
      run: python3 .github/workflows/gnotify.py
