name: notify-gchat-on-issue-comment
on: issue_comment
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Git Details
      run: |
        echo "Issue url: ${{ github.event.comment.issue_url }}"
        echo "Comment id: ${{ github.event.comment.id }}"
        echo "Comment url: ${{ github.event.comment.html_url }}"
        echo "Comment user: ${{ github.event.comment.user.login }}"
    - name: Google Chat Notification
      run: |
        curl --location --request POST '${{ secrets.GOOGLE_SPACE_URL }}' \
        --header 'Content-Type: application/json' \
        --data-raw '{
            "cards": [
              {
                "header": {
                  "title": "Issue Comment Tracker",
                  "subtitle": "Issue No: #${{ github.event.issue.number }}"
                },
                "sections": [
                  {
                    "widgets": [
                      {
                        "keyValue": {
                          "topLabel": "Title",
                          "content": "${{ github.event.issue.title }}"
                        }
                      },
                      {
                        "keyValue": {
                          "topLabel": "Commenter",
                          "content": "${{ github.event.comment.user.login }}"
                        }
                      },
                      {
                        "buttons": [
                          {
                            "textButton": {
                              "text": "OPEN COMMENT",
                              "onClick": {
                                "openLink": {
                                  "url": "${{ github.event.comment.html_url }}"
                                }
                              }
                            }
                          }
                        ]
                      }
                    ]
                  }
                ]
              }
            ]
          }'
